config/routes.rb
NewRails::Application.routes.draw do
  devise_for :users
  resource :home, :only => [:index, :show, :create], :controller => :home
  root :to => "home#index"
  match 'product/:id' => "home#show", :as => "product"
  
  # resources :home, :only => [:index] do
  #   collection do
  #     get 'about', :as => "about"
  #     get 'faqs',  :as => "faq"
  #     get 'privacy', :as => "privacy"
  #     get 'terms_and_conditions', :as => "terms"
  #   end
  # end
  
  
  match 'about' => "home#about", :as => "about"
  match 'faqs' => "home#faqs", :as => "faq"
  match 'privacy' => "home#privacy", :as => "privacy"
  match 'promo_mechanics' => "home#promo_mechanics", :as => "promo"
  #match 'fb/:id' => "home#social"
  match 'terms_and_conditions' => "home#terms_and_conditions", :as => "terms"
  match 'registration' => "home#signup", :as => "registration"
  match 'registration_complete' => "home#signup_complete", :as => "registration_complete"
  
end

app/models/product.rb
class Product < ActiveRecord::Base

  def permalink
    "#{self.id}_#{self.name.parameterize}"
  end
end

app/models/product_analytic.rb
class ProductAnalytic < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :registerable, :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable#, :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/user_signup.rb
class UserSignup < ActiveRecord::Base
  def created_at_date
    self.created_at.strftime("%B %d %Y")
  end
  
  def created_at_time
    self.created_at.strftime("%H:%M")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  before_filter :if => Proc.new{ |c| c.request.path =~ /admin/ } do 
    @head_stylesheet_paths = ['admin_screen.css'] 
  end
#  rescue_from CanCan::AccessDenied do |exception|
#    redirect_to root_url, :alert => exception.message
#  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    
    @products = Product.where("week_number = #{Time.now.strftime("%U")}").order("position")
    if @products.empty?
      #max = Product.max("week_number")
      #@products = Product.where("week_number = #{max}").order("position")
      @products = Product.order("position")
    end
  end
  
  def show
    @product = Product.find(params[:id].split("_")[0])
    @product.view_count = @product.view_count.to_i + 1
    @product.save
    redirect_to  "#{@product.product_url}?utm_source=semmicrosite%2B&utm_medium=link%2B&utm_campaign=semmicrosite%2B"
  end
  
  def signup
    create if request.post?
  end
  
  def create
    UserSignup.create(
      :multiply_user_id => params[:muid],
      :name => params[:name],
      :age  => params[:age],
      :contact_number => params[:num],
      :address => params[:add],
      :size_of_shirt => params[:size]
    )
    render "signup_complete"
  end
  
  def social
    #Cookie:  fbs_213790775324755="access_token=213790775324755%7C2.AQDPKUdO34D1xczG.3600.1309752000.1-783183828%7C7XhxJXdFMKGmoxygNn-AOm8CYbo&base_domain=www.multiplyphilippines.com&expires=1309752000&secret=PsnQ400mIzY21oXbit_j7g__&session_key=2.AQDPKUdO34D1xczG.3600.1309752000.1-783183828&sig=6fe2f3731a4bce084001637444eec602&uid=783183828";
    #cookies[:fbs_213790775324755]
    render :nothing => true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.haml
%section{:class => "content container"}
  %section{:id => "content", :class => "box container_12"}
    =render "layouts/left_pane"
    %section{:id => "about", :class => "omega grid_9"}
      %h1 About this site
      %span{:class => "imgborder"}
      %p{:class => "about"} This is an official Multiply Philippines promo site geared towards reaching out and engaging our customers. This is our way of supporting our merchants who've been with us all throughout and our way of encouraging you to support them—our local entrepreneurs.
      %p{:class => "about"} Over the years, Multiply has transitioned from your favorite social networking service to the Philippines' largest marketplace where you can practically find anything from the simplest shirt to the newest high-end gadgets and what have you.
      %br
      %br
    %section{:id => "about", :class => "omega grid_9"}
      %h1 Multiply Privacy Policy
      %span{:class => "imgborder"}
      %p{:class => "about"} The disclosure of personal information is always a sensitive issue and Multiply takes it very seriously. We consider it our highest priority to protect the privacy of our members. To that end, this privacy policy outlines the types of information Multiply collects and how that information is used in the operation of our site. All information that Multiply collects will adhere to this privacy policy and will be used for the sole purpose of providing you a highly personalized and interactive experience with our site. No personal information collected from our members will ever be sold or leased to any third party without the proper consent.
      %p{:class => "about"} 
        Questions regarding this privacy policy should be sent via email at 
        %a{:href => "mailto:csph@multiply.com"} csph@multiply.com 
      %h2 About the Information We Collect and How We Use it
      %ol{:id => "tableofcontents"}
        %li
          %h3 1. Registration
          %p{:class => "about"} To join the Multiply promo, we need to ask you for some details: Multiply user ID, Name, Age, Mobile Number, Address, E-mail.  Your Multiply ID and e-mail address is used to identify you in the Multiply system with your online purchase if you qualify for the promo.  Your shirt will be shipped to you with the address you’ve provided.  Multiply will never share your personal information with any non-registered user of our site or third party company or person without your explicit consent. 
        %li
          %h3 2. Consent and Modification 
          %p{:class => "about"} By using this Site, you consent to the terms of our Privacy Policy and to Multiply’s processing of Personal Information for the purposes set forth herein.  If you do not agree to this Privacy Policy at any time, please do not use our Site.  Multiply reserves the right to update our privacy policy. Please check this page occasionally to make sure you are aware of any updates.
        %li
          %h3 3. Children
          %p{:class => "about"} In compliance with the Children's Online Privacy Protection Act (COPPA), we will not knowingly provide access to Multiply to persons under the age of thirteen (13). If Multiply later learns that a member is under the age of thirteen (13) we will take appropriate steps to remove the member's information from the database and restrict the individual from future access to the Multiply service.
      %h2 With Whom Information May Be Shared
      %ol{:id => "tableofcontents"}
        %li
          %h3 1. Third Parties
          %p{:class => "about"} Multiply will not sell or lease your personal information to third parties without your explicit consent, unless required by law. We may share your information with third parties under certain circumstances:
          %p{:class => "about"}  if sharing your information is necessary to execute a specific request by you (e.g., purchasing premium services via credit card, in which case it would be necessary to share your information with a credit card processing company). In these specific cases third parties will not retain, share or store any personally identifiable information except to provide the specific services requested by you, and are bound by strict confidentiality agreements which limit their use of such information.
          %p{:class => "about"}  if sharing your information is required by law or is necessary to respond to a subpoena, warrant or court order, or to protect the rights of Multiply or its members.
          %p{:class => "about"}  if you give us explicit permission to share your information for any reason not stated in this privacy policy.
        %li
          %h3 2. Links to Other Web Sites
          %p{:class => "about"} You may occasionally see links to other web sites on Multiply, either via advertisements or other third-party promotions or links posted by other Multiply members. Multiply is not responsible for the privacy practices of other sites you may visit through a link you found on Multiply. If you provide information directly to a party other than Multiply, different privacy policies may cover those parties' use of your information. Please review any company's privacy policy before disclosing your personal information.
          
      %h2 Security
      %p{:class => "about"} Multiply has implemented security measures to protect member information from loss, misuse and alteration. We use industry-standard practices such as encrypted storage, firewalls and password protection systems to safeguard the confidentiality of your personal information. Each of our employees is aware of our security policies, and your information is only available to those employees who need it to perform their jobs.
      
      %br
      =link_to("Shop at Multiply Marketplace", "http://multiply.com/marketplace?utm_source=semmicrosite%2B&utm_medium=link%2B&utm_campaign=semmicrosite%2B", :class => "shop btn", :rel => "external", :target => "_blank")

app/views/home/faqs.html.haml
%section{:class => "content container"}
  %section{:id => "content", :class => "box container_12"}
    =render "layouts/left_pane"
    %section{:id => "faqs", :class => "omega grid_9"}
      %h1 FAQs
      %span{:class => "imgborder"}
      %ol{:id => "tableofcontents"}
        %li=link_to("Who are the qualified winners for this promo?", "#faq1")
        %li=link_to("How do I get the shirt?", "#faq2")
        %li=link_to("When do I get the shirt?", "#faq3")
        %li=link_to("How often can I claim a shirt?", "#faq4")
        %li=link_to("Can I buy from multiple stores?", "#faq5")
        %li=link_to("How long is the promo?", "#faq6")
        %li=link_to("What is the Multiply Payment Facility?", "#faq7")
        %li=link_to("I have other questions, how can I reach Multiply Philippines?", "#faq8")
      %br
      %br
      %ol
        %li{:id => "faq1"}
          1) Who are the qualified winners for this promo?
          %ul
            %li
              a) You must be a registered Multiply user aged 18 years old and above.
            %li
              b) An order # claim should amount to at least Php 500.
        %li{:id => "faq2"}
          2) How do I get the shirt?
          %ul
            %li
              Your shirt will be delivered to the address you’ve shared with us upon verification of your order # amounting to at least Php 500.
        %li{:id => "faq3"}
          3) When do I get the shirt?
          %ul
            %li
              At the most 4-6 weeks upon validation and verification of your registration and order # amounting to at least Php 500.
        %li{:id => "faq4"}
          4) How often can I claim a shirt?
          %ul
            %li
              You can claim as much shirts as you want provided that you have equal amounts of order # claims amounting to at least Php 500 each.
        %li{:id => "faq5"}
          5) Can I buy from multiple stores?
          %ul
            %li
              Yes you may buy from multiple stores to meet the Php 500 requirement per order #.
        %li{:id => "faq6"}
          6) How long is the promo?
          %ul
            %li
              Promo duration from July 11 to Oct 2, 2011
        %li{:id => "faq7"}
          7) What is the Multiply Payment Facility?
          %ul
            %li
              a) The Multiply payment facility is our initiative to help you purchase from Multiply sellers faster. It basically works like similar shopping cart and checkout facilities.
            %li
              b) Just look for the "Buy Now" (buy the item now) and "Inquire" (haggle with the seller first) button and it will direct you to the Multiply payment and checkout process.
        %li{:id => "faq8"}
          8) I have other questions, how can I reach Multiply Philippines?
          %ul
            %li
              Please email us at 
              %a{:href => "mailto:csph@multiply.com"}csph@multiply.com
              for any inquiry.
      %br
      =link_to("Shop at Multiply Marketplace", "http://multiply.com/marketplace?utm_source=semmicrosite%2B&utm_medium=link%2B&utm_campaign=semmicrosite%2B", :class => "shop btn", :rel => "external", :target => "_blank")

app/views/home/index.html.haml
%section{:class => "content container"}
  %section{:id => "content", :class => "box container_12"}
    =render "layouts/left_pane"
    %section{:class => "omega grid_9"}
      %h1 
        %img{:src => "/images/trusted-32.png", :width => "20px"}
        Here are some products you can get from Multiply to get your Multiply Tee:
      %span{:class => "imgborder"}
      %ul{:class => "items"}
        - @products[0..15].each_with_index do |product, index|
          %li{:class => ((index.modulo(4) == 0)? "first " : (index.modulo(4) == 3 || index == @products.size - 1)? "last " : "") + "product"}
            .placeholder
              = link_to(image_tag(product.image_url, :alt => product.name, :title => "Buy #{product.name}", :width => "148px", :height => "140px"), product_url(product.permalink), :target => "_blank", :rel => "external")
            =link_to(product.name, product_url(product.permalink), :target => "_blank", :rel => "external")
            %br
            %span Buy it from
            =link_to(product.seller, "http://#{product.seller.delete(" ").downcase}.multiply.com", :target => "_blank", :rel => "external")
      %ul{:class => "items", :id => "other_items", :style => "display:none;"}
        - begin
          - @products[16..-1].each_with_index do |product, index|
            %li{:class => ((index.modulo(4) == 0)? "first " : (index.modulo(4) == 3 || index == @products.size - 1)? "last " : "") + "product"}
              .placeholder
                = link_to(image_tag(product.image_url, :alt => product.name, :title => "Buy #{product.name}", :width => "148px", :height => "140px"), product_url(product.permalink), :target => "_blank", :rel => "external")
              =link_to(product.name, product_url(product.permalink), :target => "_blank", :rel => "external")
              %br
              %span Buy it from
              =link_to(product.seller, "http://#{product.seller.delete(" ").downcase}.multiply.com", :target => "_blank", :rel => "external")
        - rescue
      %span{:class => "imgborder"}
      =link_to("View More items from Multiply Trusted Sellers", "javascript:void(0)", :class => "viewmore btn") if @products.size > 16
      %br
      %br
      =link_to("Shop at Multiply Marketplace", "http://multiply.com/marketplace?utm_source=semmicrosite%2B&utm_medium=link%2B&utm_campaign=semmicrosite%2B", :class => "shop btn", :rel => "external", :target => "_blank")

app/views/home/privacy.html.haml
%section{:class => "content container"}
  %section{:id => "content", :class => "box container_12"}
    =render "layouts/left_pane"
    %section{:class => "omega grid_9"}
      %h1 About this site:
      = image_tag("borderContent.png", :class => "imgborder")
      %p{:class => "about"} This is an official Multiply Philippines promo site geared towards reaching out and engaging our customers. This is our way of supporting our merchants who've been with us all throughout and our way of encouraging you to support them-our local entrepreneurs.
      %p{:class => "about"} Over the years, Multiply has transitioned from your favorite social networking service to the Philippines' largest marketplace where you can practically find anything from the simplest shirt to the newest high-end gadgets and what have you.
      %br
      =link_to("Shop at Multiply Marketplace", "http://multiply.com/marketplace?utm_source=semmicrosite%2B&utm_medium=link%2B&utm_campaign=semmicrosite%2B", :class => "shop btn", :rel => "external", :target => "_blank")

app/views/home/promo_mechanics.html.haml
%section{:class => "content container"}
  %section{:id => "content", :class => "box container_12"}
    =render "layouts/left_pane"
    %section{:id => "about", :class => "omega grid_9"}
      %h1 Promo Mechanics
      %span{:class => "imgborder"}
      %h2 QUALIFICATIONS/DISQUALIFICATIONS OF PARTICIPANTS:
      %ol{:id => "tableofcontents"}
        %li
          %p{:class => "about"} 1. Open to Filipino citizens or Philippine residents, who are at least18 years of age at the time of joining, and with registered mailing addresses in the Philippines.
        %li
          %p{:class => "about"} 2. MultiplyPhilippines,McCann Worldgroup Philippines (MRM Worldwide)and other official media partners and sponsors' employees and their relatives up to the second degree of consanguinity are disqualified from joining. 
        %li
          %p{:class => "about"} 3. Must have completed and submitted the applications form on multiplyphilippines.com
        %li
          %p{:class => "about"} 4. Must have a registered Multiply ID. 
        %li
          %p{:class => "about"} 5. Promotion period is from July 11,2011 to October 10, 2011
      %h2 DESCRIPTION OF PROCEDURES:
      %p{:class => "about"} A. How to Join and How to Participate:
      %ol{:id => "tableofcontents"}
        %li
          %p{:class => "about"} 1. Those qualified and interested to join must click on the "Register Now" link on multiplyphilippines.com listed under the "Get Your Shirt Now!" box.
        %li
          %p{:class => "about"} 2. On the application form, qualified and interested persons (hereinafter referred to as "participant") will be asked to register their complete name, age, contact numbers, address,email address, Multiply ID, size of shirt and agreement to abide by the mechanics of theMultiply Philippinespromotion (hereinafter referred to as "promotion") before they can be allowed to join.
        %li
          %p{:class => "about"} 3. For a minimum purchase of Php 500 in a single order receipt, the participant is qualified for one Multiply Limited Edition Shirt.
        %li
          %p{:class => "about"} 4. To join the promotion, participant must:
          %p{:class => "about"}
            &nbsp;&nbsp;&nbsp;&nbsp;a.	Go tomultiplyphilippines.com
            %br
            &nbsp;&nbsp;&nbsp;&nbsp;b.	Click on the "Register Now" link under the "Get Your Shirt Now!" button. Complete all the required fields of the form. 
            %br 
            &nbsp;&nbsp;&nbsp;&nbsp;c.	Purchase a single order receipt minimum of Php 500 from any Multiply merchant.
            %br
            &nbsp;&nbsp;&nbsp;&nbsp;d.	Wait for Multiply to send you a personal message on Multiply and email notifying you that you are eligible for a limited edition shirt.
      %p{:class => "about"} B. Promo Mechanics 
      %ol{:id => "tableofcontents"}
        %li
          %p{:class => "about"} 1. Participant should do the following steps to join the promo: 
          %p{:class => "about"}
            &nbsp;&nbsp;&nbsp;&nbsp;a. STEP 1: Shop from any Multiply merchant using the Multiply payment gateway.
            %br
            &nbsp;&nbsp;&nbsp;&nbsp;b. STEP 2: Purchase a minimum of Php 500 worth of items
            %br 
            &nbsp;&nbsp;&nbsp;&nbsp;c. STEP 3: Give us your details, and we'll send you a shirt! 
      %p{:class => "about"} B. How to Claim Prizes and Period of Redemption
      %ol{:id => "tableofcontents"}
        %li
          %p{:class => "about"} 1. Qualified participant's purchases will be automatically checked through Multiply's backend system. Eligible participants of the Limited Edition promo will be notified via personal message on Multiply and via email.
        %li
          %p{:class => "about"} 2. Multiply Philippines will send the Limited Edition Multiply Shirts, upon validation of purchase, to the mailing address listed in the submitted application form. Multiply will mail the shirts to participants with registered mailing addresses in the Philippines within 60 days of the receipt of mail notification. 
        %li
          %p{:class => "about"} 3. All shirts are non-transferable and not convertible to cash.         
      %p{:class => "about"} D. Promo Duration 
      %ol{:id => "tableofcontents"}
        %li
          %p{:class => "about"} 1. Participants will only be eligible to win a Limited Edition shirt if Php 500 single order receipt is purchased on Multiply.com from July 11, 2011 at 12:01 am to October 10, 2011 11:59 pm. 
      %p{:class => "about"} E. Claiming Prizes and Period of Redemption 
      %ol{:id => "tableofcontents"}
        %li
          %p{:class => "about"} 1. Qualified participant purchases will be automatically checked through Multiply’s backend system.Winners of the Limited Edition promo will be notified via personal message on Multiply and via email. 
        %li
          %p{:class => "about"} 2. Multiply will mail the shirts to winning participants with registered mailing addressesin the Philippines within 60 days of the receipt of mail notification.
      %p{:class => "about"} F. OTHER GUIDELINES:
      %ol{:id => "tableofcontents"}
        %li
          %p{:class => "about"} 1. By joining and participating in this promotion, participants confirm, agree to and acknowledge that:
          %p{:class => "about"}
            &nbsp;&nbsp;&nbsp;&nbsp;a. Multiply Philippines is permitted to receive his/her registration data and that all personal information supplied by him/her will be used by Multiply Philippines in accordance with its privacy policy;
            %br
            &nbsp;&nbsp;&nbsp;&nbsp;b.	Organizers of the promotions have the right to identify him or her as an eligible participant in the promotions and communicate the same at any time in any territory through any medium of release (mass media, digital media, etc.)
            %br 
            &nbsp;&nbsp;&nbsp;&nbsp;c.	Organizers of the promotions may, without further compensation to him/her to: (a) to reproduce, distribute, adapt, modify, make available and/or communicate to the public, exhibit, or broadcast the entries he/she submitted by any means or media without restriction of any kind as to quantity, purpose or time, whether commercial or otherwise, or to any country or territory in the world; and (b) to authorize any of the above activities;
            &nbsp;&nbsp;&nbsp;&nbsp;d.	He/she shall make no reproduction of any part of the websites herein for purposes of selling or distributing the same for commercial gain nor shall he/she modify or incorporate any part of the websites herein in any other work, publication or website.
      %br
      =link_to("Shop at Multiply Marketplace", "http://multiply.com/marketplace?utm_source=semmicrosite%2B&utm_medium=link%2B&utm_campaign=semmicrosite%2B", :class => "shop btn", :rel => "external", :target => "_blank")

app/views/home/signup.html.haml
%section{:class => "content container"}
  %section{:id => "content", :class => "box container_12"}
    =render "layouts/left_pane"
    %section{:class => "omega grid_9"}
      %h1 Register to get your Multiply Tee now!
      %span{:class => "imgborder"}
      =form_tag(registration_path, :id => "signup_form") do
        %ul{ :id => "signup"}
          %li{ :class => "signupForm"}
            %ul
              %li{ :class => "label"}
                %h2
                  Multiply ID
                  %span{ :class => "red"} *
              %li{ :class => "textfield"}=text_field_tag("muid", "", :placeholder => "kimstore", :class => "required")
          %li{ :class => "signupForm"}
            %ul
              %li{ :class => "label"}
                %h2
                  Name
                  %span{ :class => "red"} *
              %li{ :class => "textfield"}=text_field_tag("name", "", :placeholder => "John Doe", :class => "required")
          %li{ :class => "signupForm"}
            %ul
              %li{ :class => "label"}
                %h2
                  Age
                  %span{ :class => "red"} *
              %li{ :class => "textfield"}=text_field_tag("age", "", :placeholder => "18", :class => "required digits", :minlength => "2", :maxlength => 2)
          %li{ :class => "signupForm"}
            %ul
              %li{ :class => "label"}
                %h2
                  Contact Number
                  %span{ :class => "red"} *
              %li{ :class => "textfield"}=text_field_tag("num", "", :placeholder => "6300012345678", :class => "required digits")
          %li{ :class => "signupForm"}
            %ul
              %li{ :class => "label"}
                %h2
                  Address
                  %span{ :class => "red"} *
              %li{ :class => "textfield"}=text_field_tag("add", "", :placeholder => "1 San Miguel Ave", :class => "required")
          %li{ :class => "signupForm"}
            %ul
              %li{ :class => "label"}
                %h2
                  Size of Shirt
                  %span{ :class => "red"} *
              %li{ :class => "textfield"}=text_field_tag("size", "", :placeholder => "Small", :class => "required")
          %li{ :class => "signupForm"}
            %ul
              %li{ :class => "label"}
                %h2
                  =check_box_tag("checkbox", "", false, :class => "required")
                  %span{ :class => "red"}*
              %li{ :class => "textfield", :id => "checkbox_text"}
                I agree to abide by the 
                =link_to("mechanics", promo_url)
                of the Multiply Limited Edition Promo
        %button{:class => "registered submit btn", :type => "submit", :id => "submit_btn"} Submit
        =image_tag("loading.gif", :id => "submit_loader")
      #signupDet
        %span{:class => "red"} *
        Required Fields

app/views/layouts/_flashes.html.haml
#flash
  - flash.each do |key, value|
    .message{ :class => key }
      %p= value

app/views/layouts/_left_pane.html.haml
%aside{:class => "alpha grid_3"}
  %section{:id => "howtoBox"}
    =link_to(image_tag("multiply.png"), root_url)
    %br
    =link_to(image_tag("/images/arrow.png") + " Sign In", "http://multiply.com/user/signin", :rel => "external", :target => "_blank", :class => "sign_in_link")
    %h2 Here's How to Claim Your Shirt:
    %ul{ :id => "posts-list"}
      %li
        %section{:class => "post-number first"}
        %section{:class => "post-content"} Shop a minimum of Php 500 worth of items from any Multiply seller.
      %li
        %section{:class => "post-number second"}
        %section{:class => "post-content"} Pay through the new payment facility (look for the "buy now" or "inquire" button).
      %li{:class => "last"}
        %section{:class => "post-number third"}
        %section{:class => "post-content"} Register here and tell us who and where to ship the shirts to.
  =link_to("Claim Your Cash", registration_url, :class => "forms claim btn")
  %ul{:id => "socialmedia"}
    %li
      %fb:like{:href => "https://www.multiplypromos.com/", :send => "false", :layout => "button_count", :width => "220", :height => "27", :show_faces => "true", :font => "verdana"}
    %li
      %iframe{:allowtransparency => "true", :frameborder => "0", :scrolling => "no", :src =>"http://platform.twitter.com/widgets/tweet_button.html?url=https://multiplypromos.com&via=shopatmultiply&count=horizontal&text=Shop%20from%20over%20125,000%20Multiply%20stores%20and%20support%20local%20entrepreneurs!%20Get%20great%20deals%20for%20electronics,%20gadgets,%20clothing,%20shoes,%20toys,%20and%20many%20more.", :style => "width:140px; height:27px;"}
    %li
      %g:plusone{:size => "medium", :href => "https://multiplyphilippines.com"}
  %section{:id => "twitter-box"}
    %h2
      %span{:class => "twitterIcn"}
      Twitter
    .socialmediabox
      :javascript
        new TWTR.Widget({ version: 2, type: "profile", rpp: 7, interval: 6000, width: 220, height: 300, creator: true,
          theme: {
            shell: { background: "#eae9e6", color: "#000000" },
            tweets: { background: "#eae9e6", color: "#000000", links: "#456f9b" }
          },
          features: { scrollbar: false, loop: false, live: false, hashtags: true, timestamp: true, avatars: false, behavior: "all" }
        }).render().setUser("shopatmultiply").start();
  %section{:id => "facebook-box"}
    %h2
      %span{:class => "facebookIcn"}
      Facebook
    .socialmediabox
      =link_to("Shop at Multiply", "http://www.facebook.com/shopatmultiply", :target => "_TOP", :style => "font-family: &quot;lucida grande&quot;,tahoma,verdana,arial,sans-serif; font-size: 11px; font-variant: normal; font-style: normal; font-weight: normal; color: #3B5998; text-decoration: none;", :title => "Shop at Multiply")
      %br
      =link_to(image_tag("http://badge.facebook.com/badge/172651079453591.1937.470419547.png", :width => "120", :height => "400", :style => "border:0px"), "http://www.facebook.com/shopatmultiply", :target => "_TOP", :title => "Shop at Multiply")
      %br
      =link_to("Promote Your Page Too", "//www.facebook.com/business/dashboard/", :target => "_TOP", :style => "font-family: &quot;lucida grande&quot;,tahoma,verdana,arial,sans-serif; font-size: 11px; font-variant: normal; font-style: normal; font-weight: normal; color: #3B5998; text-decoration: none;", :title => "Make your own badge!")

app/views/layouts/_stylesheets.html.haml
= stylesheet_link_tag "application", :media => "all"
= yield :stylesheets

app/views/layouts/application.html.haml
!!! 5
-ie_html :class => 'no-js', :lang => 'en' do
  %head
    = render "layouts/head", :stylesheet_partial => "layouts/stylesheets"
  %body{ :class => "home", :id => "index" }
    %section{ :class => "nav container" }
      %nav{ :class => "box container_12" }
        %section{ :id => "logo" }
          =link_to(image_tag("multiply.png"), root_url)
        %ul{ :id => "navigation" }
          %li=link_to("Home", root_url)
          %li=link_to("Shop at Multiply", "http://multiply.com/marketplace?utm_source=semmicrosite%2B&utm_medium=link%2B&utm_campaign=semmicrosite%2B", :rel => "external", :target => "_blank")
          %li=link_to("About", about_url)
          %li=link_to("FAQs", faq_url)
          %li=link_to("Promo Mechanics", promo_url)
    %section{:class => "header container"}
      %header{:class => "box container_12", :style => "height:250px;position:relative"}
        %span{:id => "dti"}
          Per DTI-NCR Permit #6788 Series of 2011. 
          =link_to("Click here for details.", promo_url)
        %aside{:class => "alpha grid_3", :style => "position:absolute;width:220px;bottom:10px;right:20px"}
          =link_to("Claim Your Shirt", registration_url, :class => 'forms claim btn', :style => "height:43px")
    #fb-root
    :javascript
      window.fbAsyncInit = function() {
        FB.init({appId: '213790775324755', status: true, cookie: true, xfbml: true});
      };
      (function() {
        var e = document.createElement('script'); e.async = true;
        e.src = document.location.protocol + '//connect.facebook.net/en_US/all.js';
        document.getElementById('fb-root').appendChild(e);
      }());
    = yield
    %footer{:class => "box container_12" }
    /= render "layouts/signup"
    /= render "layouts/signup_complete"
    = render "layouts/javascripts"